FROM docker.io/eclipse-mosquitto:2.0.15-openssl


RUN apt-get update \
&& apt-get upgrade \
&& apt-get install git \
&& git clone 

RUN mkdir -p /mosquitto/config /mosquitto/data  /mosquitto/log && chown -R mosquitto:mosquitto /mosquitto/config /mosquitto/data /mosquitto/log
RUN git
