version: "3.8"

services:
  mqtt:
    image: arm64v8/eclipse-mosquitto:2.0.15-openssl
    hostname: mosquitto
    ports:
      # MQTT encrypted TCP 8883
      - mode: host
        target: 8883
        published: 8883
        protocol: tcp
    networks:
      - mqtt-net1
    volumes:
      - type: bind
        source: config/mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
      - type: bind
        source: config/certs
        target: /mosquitto/config/certs
      - type: bind
        source: data/
        target: /mosquitto/data
      - type: bind
        source: log/
        target: /mosquitto/log
    deploy:
      labels:
        local.description: "Mosquitto MQTT by AXMOS"
      restart_policy:
        condition: on-failure

networks:
  mqtt-net1: